sudo: false
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

before_install:
- mv config/config.example.js config/config.js

install:
  - npm install
  - npm install -g codecov
  - npm install istanbul
  - npm install @react-navigation/native

script:
  - npm test
  - node ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- --reporter spec --check-leaks -u exports -R spec test/**/*.mocha_spec.js src/**/*
  - codecov
